// <auto-generated />
namespace Proekt_IT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LikedWallpaperchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LikedWallpaperchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202409112322117_LikedWallpaper-changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
